# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\workspace\pythonworkspace\wasucti\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QAxContainer import QAxWidget
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("UCCE CTIOS")
        MainWindow.resize(1039, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 971, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.log = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        self.clearlog = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearlog.setObjectName("clearlog")
        self.verticalLayout.addWidget(self.clearlog)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 969, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkin = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.checkin.setObjectName("checkin")
        self.checkin.setDisabled(True)
        self.horizontalLayout.addWidget(self.checkin)
        self.checkout = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.checkout.setObjectName("checkout")
        self.checkout.setDisabled(True)
        self.horizontalLayout.addWidget(self.checkout)
        self.ready = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ready.setObjectName("ready")
        self.ready.setDisabled(True)
        self.horizontalLayout.addWidget(self.ready)
        self.busy = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.busy.setObjectName("busy")
        self.busy.setDisabled(True)
        self.horizontalLayout.addWidget(self.busy)
        self.after = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.after.setObjectName("after")
        self.after.setDisabled(True)
        self.horizontalLayout.addWidget(self.after)
        
        self.answer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.answer.setObjectName("answer")
        self.answer.setDisabled(True)
        self.horizontalLayout.addWidget(self.answer)

        self.handup = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.handup.setObjectName("handup")
        self.handup.setDisabled(True)
        self.horizontalLayout.addWidget(self.handup)

        self.connect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connect.setObjectName("connect")
        self.connect.setDisabled(True)
        self.horizontalLayout.addWidget(self.connect)


        self.delete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete.setObjectName("重新加载")
        #self.connect.setDisabled(True)
        self.horizontalLayout.addWidget(self.delete)

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 591, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_cti = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_cti.setObjectName("label_cti")
        self.horizontalLayout_2.addWidget(self.label_cti)
        self.lineEdit_cti = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_cti.setObjectName("lineEdit_cti")
        self.horizontalLayout_2.addWidget(self.lineEdit_cti)
        self.label_ext = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_ext.setObjectName("label_ext")
        self.horizontalLayout_2.addWidget(self.label_ext)
        self.lineEdit_ext = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_ext.setObjectName("lineEdit_ext")
        self.horizontalLayout_2.addWidget(self.lineEdit_ext)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loadActivex()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def loadActivex(self):
        self.axWidget = QAxWidget("activex")
        self.axWidget.setControl("ax.cti")
        #self.axWidget.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        #self.axWidget.setProperty("DisplayAlerts", False)
        #self.axWidget.setProperty("DisplayScrollBars", True)
        #self.axWidget.setHidden(True)
        self.horizontalLayout_2.addWidget(self.axWidget)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status.setText(_translate("MainWindow", "状态"))
        self.clearlog.setText(_translate("MainWindow", "清除日志"))
        self.checkin.setText(_translate("MainWindow", "签入"))
        self.checkout.setText(_translate("MainWindow", "签出"))
        self.ready.setText(_translate("MainWindow", "就绪"))
        self.busy.setText(_translate("MainWindow", "示忙"))
        self.after.setText(_translate("MainWindow", "话后"))
        self.connect.setText(_translate("MainWindow", "connect"))
        self.answer.setText(_translate("MainWindow", "应答"))
        self.handup.setText(_translate("MainWindow", "挂机"))
        self.delete.setText(_translate("MainWindow", "手动连接"))
        self.label_cti.setText(_translate("MainWindow", "CTI号"))
        self.label_ext.setText(_translate("MainWindow", "分机号"))

