# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\workspace\pythonworkspace\wasucti\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QAxContainer import QAxWidget
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #layout
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 261, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        #button
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.clickButton)
        #
        self.axWidget = QAxWidget("activex", self)
        self.axWidget.setControl("ax.cti")
        self.axWidget.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.axWidget.setProperty("DisplayAlerts", False)
        self.axWidget.setProperty("DisplayScrollBars", True)
        self.verticalLayout.addWidget(self.axWidget)
        
        #self.axWidget.dynamicCall("InitControl(const QString&,const QString&,const QString&,const QString&,const QString&,const QString&)","30.209.222.14", "42028", "30.209.223.14", "42028", "D:\\log\\", "7001")
        #self.axWidget.OnConnectCtiSuccedEvent.connect(self._OnConnectCtiSuccedEvent)
        #self.axWidget.OnAgentStateEnableEvent[bool,bool,bool,bool,bool].connect(self._OnAgentStateEnableEvent)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def _OnConnectCtiSuccedEvent(self):
        print("receive event")
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

    def clickButton(self):
        sender = self.sender()
        print(sender.text() + '被点击')
        self.axWidget.dynamicCall("AgentLogon(const QString&, const QString&, const QString&)",'69244','123456','69092'); 

    #def _OnAgentStateEnableEvent(self, logon, notready, ready, workready, logoff):
    #   print("logon=%s, notready=%s, ready=%s, workready=%s, logoff=%s" %(logon, notready, ready, workready, logoff) )
